/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  taocy
 * Created: 11/04/2018
 */

# 原则上是所有的id都修改成为BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT FIRST

# 3.1 e_tcc表，用于各类热力图显示，保存的是卡口或停车场等区域的单位时间通车量
ALTER TABLE `vas_b`.`e_tcc` 
ADD COLUMN `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`);

ALTER TABLE `vas_b`.`e_tcc` 
CHANGE COLUMN `e_id` `e_id` VARCHAR(100) NOT NULL COMMENT '停车场编号' ,
CHANGE COLUMN `e_jingdu` `e_jingdu` DOUBLE NULL DEFAULT NULL COMMENT '经度' ,
CHANGE COLUMN `e_weidu` `e_weidu` DOUBLE NULL DEFAULT NULL COMMENT '纬度' ,
CHANGE COLUMN `querytime` `querytime` DATETIME NULL DEFAULT NULL COMMENT '统计时间' ,
CHANGE COLUMN `count` `count` INT(11) NULL DEFAULT NULL COMMENT '数量，表示某卡口或停车场单位时间内的通车量' ,
CHANGE COLUMN `sjly` `sjly` INT(11) NULL DEFAULT NULL COMMENT '数据来源，1 停车场，2 路网，3 拥堵点，4 大车流，5 113卡口，6 检查站，7 核录' ;

#3.2 sc_alarminfo 预警信息表，用于保存各类提醒信息，实际上类似于收件箱
ALTER TABLE `vas_b`.`sc_alarminfo` 
CHANGE COLUMN `id` `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `readState` `readState` TINYINT(3) UNSIGNED ZEROFILL NULL COMMENT '读取状态，0 未读，1 已读，9 已删除' ,
CHANGE COLUMN `pushState` `pushState` TINYINT(3) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT '推送状态，0 未推送，1 已推送' ,
ADD COLUMN `receiver` VARCHAR(255) NULL COMMENT '接收者用户名' AFTER `pushState`,
ADD COLUMN `message` VARCHAR(2048) NULL COMMENT '预警信息内容' AFTER `receiver`;

#3.3 sc_bdqcl 被盗抢车辆，这是从情报获取的数据表
ALTER TABLE `vas_b`.`sc_bdqcl` 
CHANGE COLUMN `ID` `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水号' ,
ADD PRIMARY KEY (`ID`);

#3.4 sc_blacklist 黑名单，用于布控
ALTER TABLE `vas_b`.`sc_blacklist` 
CHANGE COLUMN `id` `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `auditResults` `auditResults` TINYINT(3) UNSIGNED NULL DEFAULT NULL COMMENT '审核结果，0 未审核，1 审核通过，2 审核不通过' ,
ADD COLUMN `endTime` DATE NULL COMMENT '截止时间' AFTER `auditOpinion`,
ADD COLUMN `status` TINYINT(3) ZEROFILL UNSIGNED NULL COMMENT '当前状态：0 有效，1 无效，2 删除' AFTER `endTime`;

#3.5 sc_brand

#3.6 sc_dtcldzdan 动态车辆电子档案
ALTER TABLE `vas_b`.`sc_dtcldzdan` 
CHANGE COLUMN `abnormal` `abnormal` FLOAT(6,2) NULL DEFAULT NULL COMMENT '出行异常指数' ,
CHANGE COLUMN `violation` `violation` FLOAT(6,2) NULL DEFAULT NULL COMMENT '违章异常指数' ,
CHANGE COLUMN `nightOut` `nightOut` FLOAT(6,2) NULL DEFAULT NULL COMMENT '昼伏夜出指数' ,
CHANGE COLUMN `highrisk` `highrisk` FLOAT(6,2) NULL DEFAULT NULL COMMENT '高危地区指数' ,
CHANGE COLUMN `accident` `accident` FLOAT(6,2) NULL DEFAULT NULL COMMENT '事故异常指数' ,
CHANGE COLUMN `hidden` `hidden` FLOAT(6,2) NULL DEFAULT NULL COMMENT '隐匿车辆指数' ,
CHANGE COLUMN `limits` `limits` FLOAT(6,2) NULL DEFAULT NULL COMMENT '限行分析指数' ,
CHANGE COLUMN `summary` `summary` FLOAT(6,2) NULL DEFAULT NULL COMMENT '综合异常指数' ,
CHANGE COLUMN `overSpeed` `overSpeed` FLOAT(6,2) NULL DEFAULT NULL COMMENT '频繁超速指数' ,
CHANGE COLUMN `ContViolation` `ContViolation` FLOAT(6,2) NULL DEFAULT NULL COMMENT '连续违章指数' ,
CHANGE COLUMN `abTravel` `abTravel` FLOAT(6,2) NULL DEFAULT NULL COMMENT '异常轨迹指数' ,
CHANGE COLUMN `wander` `wander` FLOAT(6,2) NULL DEFAULT NULL COMMENT '重点区域徘徊指数' ,
CHANGE COLUMN `efence` `efence` FLOAT(6,2) NULL DEFAULT NULL COMMENT '电子围栏高危地区分析指数' ,
CHANGE COLUMN `multiPlate` `multiPlate` FLOAT(6,2) NULL DEFAULT NULL COMMENT '套牌指数' ,
ADD COLUMN `sensitive` FLOAT(6,2) NULL COMMENT '敏感地区' AFTER `sfz`,
ADD COLUMN `robbery` FLOAT(6,2) NULL COMMENT '盗抢车辆' AFTER `sensitive`,
ADD COLUMN `obscured` FLOAT(6,2) NULL COMMENT '遮挡号牌' AFTER `robbery`,
ADD COLUMN `faceCover` FLOAT(6,2) NULL COMMENT '遮挡面部' AFTER `obscured`,
ADD COLUMN `noPlate` FLOAT(6,2) NULL COMMENT '无牌' AFTER `faceCover`,
ADD COLUMN `records` FLOAT(6,2) NULL COMMENT '前科记录' AFTER `noPlate`,
ADD COLUMN `drug` FLOAT(6,2) NULL COMMENT '涉毒' AFTER `records`,
ADD COLUMN `atLarge` FLOAT(6,2) NULL COMMENT '在逃' AFTER `drug`,
ADD COLUMN `relative` FLOAT(6,2) NULL COMMENT '亲戚等关联人' AFTER `atLarge`,
ADD COLUMN `morning` FLOAT(6,2) NULL COMMENT '临晨出现' AFTER `relative`,
ADD COLUMN `address` FLOAT(6,2) NULL COMMENT '地点异常' AFTER `morning`,
ADD COLUMN `timeAbnormal` FLOAT(6,2) NULL COMMENT '时间异常' AFTER `address`,
ADD COLUMN `longStay` FLOAT(6,2) NULL COMMENT '长期留京' AFTER `timeAbnormal`,
ADD COLUMN `hugeAccident` FLOAT(6,2) NULL COMMENT '重大事故' AFTER `longStay`,
ADD COLUMN `tendency` FLOAT(6,2) NULL COMMENT '犯罪倾向' AFTER `hugeAccident`,
ADD COLUMN `black` FLOAT(6,2) NULL COMMENT '黑车指数' AFTER `tendency`;

#3.7 sc_etcptjd 车辆信息表，将停车信息与卡口信息合并的表
ALTER TABLE `vas_b`.`sc_etcptjd` 
ADD COLUMN `DeviceID` VARCHAR(255) NULL COMMENT '设备编码' AFTER `SJLY`,
ADD COLUMN `SourceID` VARCHAR(255) NULL COMMENT '来源标识' AFTER `DeviceID`,
ADD COLUMN `Direction` TINYINT NULL COMMENT '行车方向' AFTER `SourceID`,
ADD COLUMN `InfoKind` TINYINT NULL COMMENT '采集类型' AFTER `Direction`,
ADD COLUMN `Speed` SMALLINT NULL COMMENT '行车速度' AFTER `InfoKind`,
ADD COLUMN `VehicleColorDepth` SMALLINT NULL COMMENT '车辆颜色深度' AFTER `Speed`,
ADD COLUMN `NumOfPassenger` TINYINT NULL COMMENT '乘客人数' AFTER `VehicleColorDepth`,
ADD COLUMN `LaneNo` TINYINT NULL COMMENT '车道' AFTER `NumOfPassenger`,
ADD COLUMN `PlateClass` CHAR(6) NULL COMMENT '车牌类别' AFTER `LaneNo`,
ADD COLUMN `PlateColor` SMALLINT NULL COMMENT '车牌颜色' AFTER `PlateClass`,
ADD COLUMN `VehicleClass` INT NULL COMMENT '车辆类别' AFTER `PlateColor`,
ADD COLUMN `VehicleBrand` INT NULL COMMENT '车辆品牌' AFTER `VehicleClass`,
ADD COLUMN `VehicleModel` INT NULL COMMENT '车辆型号' AFTER `VehicleBrand`,
ADD COLUMN `VehicleStyles` VARCHAR(30) NULL COMMENT '车辆年款' AFTER `VehicleModel`,
ADD COLUMN `VehicleColor` SMALLINT NULL COMMENT '车辆颜色' AFTER `VehicleStyles`,
ADD COLUMN `Sunvisor` SMALLINT NULL COMMENT '遮阳板状态' AFTER `VehicleColor`,
ADD COLUMN `SafetyBelt` TINYINT NULL COMMENT '安全带状态' AFTER `Sunvisor`,
ADD COLUMN `Calling` TINYINT NULL COMMENT '打电话状态' AFTER `SafetyBelt`;

#3.8 sc_gbzdr

#3.9 sc_gsd

#3.10 sc_gwrysj 高危人员数据
ALTER TABLE `vas_b`.`sc_gwrysj` 
CHANGE COLUMN `XB` `XB` TINYINT NULL DEFAULT NULL COMMENT '性别' ,
CHANGE COLUMN `CSRQ` `CSRQ` DATETIME NULL DEFAULT NULL COMMENT '出生日期' ,
CHANGE COLUMN `SFZH` `SFZH` VARCHAR(45) NULL DEFAULT NULL COMMENT '身份证号' ,
CHANGE COLUMN `HJDQH` `HJDQH` VARCHAR(45) NULL DEFAULT NULL COMMENT '户籍地区划' ,
CHANGE COLUMN `XZDQH` `XZDQH` VARCHAR(45) NULL DEFAULT NULL COMMENT '现住地区划' ,
ADD COLUMN `id` INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
ADD COLUMN `DIANHUA` VARCHAR(255) NULL COMMENT '电话手机' AFTER `XZDXZ`,
ADD COLUMN `WANGLUO` VARCHAR(255) NULL COMMENT '网络身份' AFTER `DIANHUA`,
ADD COLUMN `MZ` VARCHAR(10) NULL COMMENT '民族' AFTER `WANGLUO`,
ADD COLUMN `SHEKONG` TINYINT NULL COMMENT '涉恐' AFTER `MZ`,
ADD COLUMN `SHEJIANG` TINYINT NULL COMMENT '涉疆' AFTER `SHEKONG`,
ADD COLUMN `SHEWEN` TINYINT NULL COMMENT '涉稳' AFTER `SHEJIANG`,
ADD COLUMN `SHEZANG` TINYINT NULL COMMENT '涉藏' AFTER `SHEWEN`,
ADD COLUMN `SHEDU` TINYINT NULL COMMENT '涉毒' AFTER `SHEZANG`,
ADD COLUMN `SHANGFANG` TINYINT NULL COMMENT '上访' AFTER `SHEDU`,
ADD COLUMN `JINGSHENBING` TINYINT NULL COMMENT '精神病' AFTER `SHANGFANG`,
ADD COLUMN `ZAITAO` TINYINT NULL COMMENT '在逃' AFTER `JINGSHENBING`,
ADD COLUMN `ZAIYA` TINYINT NULL COMMENT '在押' AFTER `ZAITAO`,
ADD COLUMN `ZHAOSHI` TINYINT NULL COMMENT '肇事肇祸' AFTER `ZAIYA`,
ADD COLUMN `DAOQIE` TINYINT NULL COMMENT '盗窃' AFTER `ZHAOSHI`,
ADD COLUMN `RUSHI` TINYINT NULL COMMENT '入室' AFTER `DAOQIE`,
ADD COLUMN `TONGXUN` TINYINT NULL COMMENT '通讯诈骗' AFTER `RUSHI`,
ADD COLUMN `PAQIE` TINYINT NULL COMMENT '扒窃' AFTER `TONGXUN`,
ADD COLUMN `DAOCHE` TINYINT NULL COMMENT '盗车' AFTER `PAQIE`,
ADD COLUMN `WEIZHU` TINYINT NULL COMMENT '维族重点人' AFTER `DAOCHE`,
ADD COLUMN `YIDAOYANGXI` TINYINT NULL COMMENT '以盗养吸' AFTER `WEIZHU`,
ADD COLUMN `QINCAI` TINYINT NULL COMMENT '侵财' AFTER `YIDAOYANGXI`,
ADD COLUMN `QIANKE` TINYINT NULL COMMENT '前科' AFTER `QINCAI`,
ADD COLUMN `GAOWEIDIQU` TINYINT NULL COMMENT '高危地区' AFTER `QIANKE`,
ADD COLUMN `ZONGHE` TINYINT NULL COMMENT '综合指数' AFTER `GAOWEIDIQU`,
ADD COLUMN `JYAQ` VARCHAR(5000) NULL AFTER `ZONGHE`;
ADD PRIMARY KEY (`id`);

# 3.11 sc_scaj 涉车案件表
ALTER TABLE `vas_b`.`sc_scaj` 
CHANGE COLUMN `ID` `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水号' ,
CHANGE COLUMN `AJBH` `AJBH` VARCHAR(255) NOT NULL COMMENT '案件编号' ,
ADD COLUMN `JINDU` DECIMAL(10,7) NULL AFTER `CPH`,
ADD COLUMN `WEIDU` DECIMAL(10,7) NULL AFTER `JINDU`,
ADD COLUMN `JYAQ` VARCHAR(5000) NULL AFTER `WEIDU`,
ADD COLUMN `GIS` GEOMETRY NULL AFTER `JYAQ`,
ADD PRIMARY KEY (`ID`),
ADD UNIQUE INDEX `AJBH_UNIQUE` (`AJBH` ASC);
